spring:
  application:
    name: auth-service
  config:
    import: configserver:http://localhost:18080   # Config Server 주소

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL} # jdbc:postgresql://localhost:5432/{DB이름}
    username: ${DB_USERNAME} # postgres
    password: ${DB_PASSWORD}

service:
  jwt:
    access-expiration: 86400000  # 24시간
    secret-key: ${service.jwt.secret-key} # 환경변수에서 가져옴

server:
  port: 19010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

openapi:
  service:
    url: http://localhost:19091 # API Gateway 포트