services:
  # postgres container
  postgres:
    image: bitnami/postgresql:latest
    platform: linux/amd64
    ports:
      - ${DB_PORTS_HOST_CONTAINER}
    environment:
      POSTGRESQL_USERNAME: ${DB_USERNAME}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres-data:/postgresql/data
    networks:
      - auth-network
      - recruitment-network
      - product-network
      - review-network
      - notification-network
      - statistics-network

  # redis container
  auth-redis:
    image: redis/redis-stack:latest
    container_name: auth-redis
    platform: linux/amd64
    ports:
      - "16379:6379"
      - "18001:8001"
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    volumes:
      - auth_redis_data:/data
    networks:
      - auth-network

  recruitment-redis:
    image: redis/redis-stack:latest
    container_name: recruitment-redis
    platform: linux/amd64
    ports:
      - "16380:6379"
      - "18002:8001"
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    volumes:
      - recruitment_redis_data:/data
    networks:
      - recruitment-network

  product-redis:
    image: redis/redis-stack:latest
    container_name: product-redis
    platform: linux/amd64
    ports:
      - "16381:6379"
      - "18003:8001"
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    volumes:
      - product_redis_data:/data
    networks:
      - product-network

  review-redis:
    image: redis/redis-stack:latest
    container_name: review-redis
    platform: linux/amd64
    ports:
      - "16382:6379"
      - "18004:8001"
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    volumes:
      - review_redis_data:/data
    networks:
      - review-network

  notification-redis:
    image: redis/redis-stack:latest
    container_name: notification-redis
    platform: linux/amd64
    ports:
      - "16383:6379"
      - "18005:8001"
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    volumes:
      - notification_redis_data:/data
    networks:
      - notification-network

  statistics-redis:
    image: redis/redis-stack:latest
    container_name: statistics-redis
    platform: linux/amd64
    ports:
      - "16384:6379"
      - "18006:8001"
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    volumes:
      - statistics_redis_data:/data
    networks:
      - statistics-network

  # zookeeper, kafka, kafka-ui containers
  zookeeper:
    image: wurstmeister/zookeeper:latest
    platform: linux/amd64
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka:latest
    platform: linux/amd64
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_READONLY: "false"
    depends_on:
      - kafka
    networks:
      - kafka-network

  # monitoring containers
  prometheus:
    image: prom/prometheus:latest
    platform: linux/amd64
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - auth-network
      - recruitment-network
      - product-network
      - review-network
      - notification-network
      - statistics-network
      - kafka-network

  loki:
    image: grafana/loki:latest
    platform: linux/amd64
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/config.yaml
    networks:
      - auth-network
      - recruitment-network
      - product-network
      - review-network
      - notification-network
      - statistics-network
      - kafka-network


volumes:
  postgres-data:
  auth_redis_data:
  recruitment_redis_data:
  product_redis_data:
  review_redis_data:
  notification_redis_data:
  statistics_redis_data: