spring:
  application:
    name: product-service
#  config:
#    import: configserver:http://localhost:18080   # Config Server 주소
  datasource:
    url: ${DB_URL}
    username: ${DB_RECRUITMENT_USERNAME}
    password: ${DB_RECRUITMENT_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${RECRUITMENT_REDIS_HOST}
      port: ${RECRUITMENT_REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format-sql: true
      use_sql_comments: true

server:
  port: 19020

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

openapi:
  service:
    url: http://localhost:19091 # API Gateway 포트