spring:
  application:
    name: notification-service
  config:
    import: configserver:http://localhost:18080   # Config Server 주소

server:
  port: 19050
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

feign:
  client:
    config:
      default:  # 모든 feign client에 적용
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      auth-service:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: full

logging:
  level:
    root: INFO
    com.trillionares.tryit: DEBUG
    org.springframework.web: DEBUG
    feign: DEBUG
    feign.Logger: DEBUG

openapi:
  service:
    url: http://localhost:19091 # API Gateway 포트

slack:
  webhook:
    url: https://hooks.slack.com/ # 임시 가짜 URL