spring:
  application:
    name: product-service
#  config:
#    import: configserver:http://localhost:18080   # Config Server 주소
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${HUB_REDIS_HOST}
      port: ${HUB_REDIS_PORT}
      username: ${HUB_REDIS_USERNAME}
      password: ${HUB_REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format-sql: true
      use_sql_comments: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 19030

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

openapi:
  service:
    url: http://localhost:19091 # API Gateway 포트